language: node_js

node_js:
    - stable

sudo: false

before_script:
    - npm install -g grunt-cli

script:
    - npm test
    - grunt

after_success:
    - 'cat ./coverage/lcov.info | ./node_modules/.bin/coveralls'
    - sh script/deploy
