language: node_js

node_js:
    - stable

sudo: false

after_success:
    - 'cat ./coverage/lcov.info | ./node_modules/.bin/coveralls'
    - npm install -g grunt-cli
    - grunt coffee doc
    - sh script/deploy
